version: "3.8"


services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      network: host
    volumes:
      - ./ui/:/app
    ports:
      - 3001:3000
    command: npm run dev
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      network: host
    volumes:
      - ./api/:/app
    ports:
      - 8001:8000
    command: python manage.py runserver

    
