# Generated by Django 5.0.1 on 2024-02-01 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_documentmodel_proccsed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=255)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.documentmodel')),
            ],
        ),
    ]
